### ISSUE TITLE
unitemp_icons.h missing

### ISSUE THREAD

**Issue by Firstyear** [quen0n/unitemp-flipperzero#12]
https://github.com/quen0n/unitemp-flipperzero/blob/master/views/General_view.c#L19 includes unitemp_icons.h, however when building:

```
applications_user/unitemp-flipperzero/views/General_view.c:19:10: fatal error: unitemp_icons.h: No such file or directory
   19 | #include "unitemp_icons.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

Looking through this repository I can't find the header file in question. Could it be that it is missing or a mistake happened in a merge? Thanks!

**Comment by quen0n** [comment]
Use fbt or ufbt for building thos app

https://github.com/flipperdevices/flipperzero-firmware/blob/dev/documentation/fbt.md

**Comment by Firstyear** [comment]
This is using fbt.
