### ISSUE TITLE
[Feature] Absolute humidity

### ISSUE THREAD

**Issue by Mywk** [quen0n/unitemp-flipperzero#2]
Would be nice to see absolute humidity implemented here.

Here is my working implementation as an example (calculation explained [here](https://github.com/Mywk/FlipperTemperatureSensor/issues/1)):

```
// Calculate absolute humidity - For more info refer to https://github.com/Mywk/FlipperTemperatureSensor/issues/1
// Calculate saturation vapour pressure first
vapour_pressure = (double)6.11 * pow(10, (double)(((double)7.5 * celsius) / ((double)237.3 + celsius)));

// Then the vapour pressure in Pa
vapour_pressure = vapour_pressure * rel_humidity;

// Calculate absolute humidity
abs_humidity = (double)2.16679 * (double)(vapour_pressure / ((double)273.15 + celsius));
```

Since we're at it, would also be nice to have a simple way of checking the temperature in fahrenheit (e.g. with a button click):
`fahrenheit = (celsius * 9 / 5) + 32;`

**Comment by quen0n** [comment]
Hello, thanks for the suggestions.

The absolute air humidity value is very rarely used by users, so this function is not planned to be added yet.
Quick changeover of the unit of measure is useful. I'll do it by holding the middle button.
