### ISSUE TITLE
Build from source

### ISSUE THREAD

**Issue by gbatalski** [quen0n/unitemp-flipperzero#20]
Hello, i don't want to download binaries from russian server because of some considerations and would like to build the plugin from source. Could you please provide some informations about the build process (linux) or at least put a link to the already existing documentation. 

Many thanks and regards,
Gena

**Comment by quen0n** [comment]
It's a pity that we failed to steal your personal bank card data, saved signals and current location

You can download the app from https://lab.flipper.net/apps/unitemp directory or build the app yourself https://github.com/flipperdevices/flipperzero-firmware/blob/dev/documentation/fbt.md

**Comment by quen0n** [comment]
But seriously, that's annoying to hear. The plugin is automatically built from source to github. It's quite difficult to do something with a plugin that harms you or your device. Many people download files and are satisfied
