### ISSUE TITLE
Does this support combined AHT20+BMP280 sensor?

### ISSUE THREAD

**Issue by spitfire** [quen0n/unitemp-flipperzero#28]
Like this one: https://www.amazon.com/Alinan-Temperature-Humidity-High-Precision-Atmospheric/dp/B0B1PYC42K

**Comment by quen0n** [comment]
Both sensors are supported by the app

**Comment by spitfire** [comment]
But I have one device with 1 set of 4 pins that has both of these sensors (see link), how do I configure that?

**Comment by quen0n** [comment]
The same as if they were separate sensors. Just connect the device to the I2C pins and add two sensors in the application

**Comment by spitfire** [comment]
Thanks, just figured out that BMP280 wasn't at a pre-set address, everything works after I've changed that.
