### ISSUE TITLE
hpa conversion is kind'a faulty 

### ISSUE THREAD

**Issue by kokein** [quen0n/unitemp-flipperzero#29]
Hi, I found out that hpa conversion is kind'a faulty.

Im using BME280 (3,3v) and it of course work fine but in "mm H", and whet trying to set "hPa" it goes crazy :)

Eg: 770 mm Hg / -> -28349,6 hPa :D (and it shuld be around 1026,58 hpa) ;) 

![20240109_110403](https://github.com/quen0n/unitemp-flipperzero/assets/12292584/b74182d2-4637-4d42-afc3-d866bbc831fe)
![20240109_110421](https://github.com/quen0n/unitemp-flipperzero/assets/12292584/68d51a75-7cc3-4fdb-b624-57671494c8c3)

Nick

**Comment by quen0n** [comment]
The plugin does not support the pressure display format that is presented on your screen
You may be using a version of the plugin with modifications from a third-party developer. The original plugin does not have this problem.
