### ISSUE TITLE
After update app only works with DHT11

### ISSUE THREAD

**Issue by I027614** [quen0n/unitemp-flipperzero#39]
After last firmware and app update (August 15) the app only works with temperature and humidity sensor DHT11 (only shows that screen) and buttons are ignored. You need to reboot the device to leave the app.

**Comment by ardaniel** [comment]
I have a BME680 on an i2c interface and it works with the current app, but I also have to reboot the Flipper to exit the app now.

**Comment by diegote386** [comment]
I have the problem, it's freeze on "press ok to add" and I touch no more working. Need reset flipper to exit.

**Comment by nicolagonella** [comment]
same problem of diegote, looking in debug log i found a message 
[W] [Unitemp] Missing sensors file

**Comment by quen0n** [comment]
The problem has been fixed

**Comment by diegote386** [comment]
> [@quen0n](https://github.com/quen0n) this problem has definitely _not_ been fixed. My Flipper still freezes on "Click 'ok' to add a sensor".

I have the same problem.

**Comment by I027614** [comment]
New firmware, same old problem.
