### ISSUE TITLE
Unitemp Error on Unleashed 0.77

### ISSUE THREAD

**Issue by stevanuscolonne** [quen0n/unitemp-flipperzero#40]
Unitemp froze on open. Tried to delete conf files result nothing.
I'm using AHT10, BMP180 & BMP280 at a time. I also tried to edit sensor.cfg to display only 1 sensor and attach only 1 sensor, it works but as soon as I touched any button then it suddenly froze. Please help to fix it🙏🙏

**Comment by quen0n** [comment]
The problem has been fixed
