### ISSUE TITLE
Current Release 1.5 does not work on firmware 1.0

### ISSUE THREAD

**Issue by igitti** [quen0n/unitemp-flipperzero#41]
With the firmware release 1.0 [https://blog.flipper.net/released-firmware-1/](https://blog.flipper.net/released-firmware-1/)
the app's current release 1.5 doesn't start: "Error: Outdated App".

Please provide an update.

Update: "Error: Outdated App" appears when the app is installed manually by downloading the latest version (see README.md) and copying the fap file to the SD card.
Now I could install it automatically with the browser. It also freezes showing "No sensors found".

**Comment by themagiccog** [comment]
I have the same issue. It just freezes here:
![Screenshot_20240925_122517_Flipper](https://github.com/user-attachments/assets/bf638959-be21-426f-9973-ee196ac01805)


Any updates @quen0n

**Comment by tiagosiebler** [comment]
Same here, freezes the flipper completely

**Comment by Decapitares** [comment]
the same problem

**Comment by mikesindieiev** [comment]
Same for me

**Comment by meixnt** [comment]
I have the same problem

**Comment by mikesindieiev** [comment]
I was able to workaround this issue. I have installed unleashed firmware and it contains v1.4 of unitemp which works like a charm.

**Comment by Greg50100** [comment]
the same problem

**Comment by vladin79** [comment]
I managed to fix this issue in the app's current release 1.5 code. It is now working on my flipper zero with the official firmware release 1.0.1. I opened pull requests with the fixes. I can also provide the built working fap file if someone needs it.

**Comment by igitti** [comment]
> I managed to fix this issue in the app's current release 1.5 code. It is now working on my flipper zero with the official firmware release 1.0.1. I opened pull requests with the fixes. I can also provide the built working fap file if someone needs it.

Hello vladin79,
I would try your fap file. Unfortunately installing the original fap file manually led to another error. See my updated opening comment above.

**Comment by vladin79** [comment]
> Hello vladin79,
> I would try your fap file. Unfortunately installing the original fap file manually led to another error. See my updated opening comment above.

Hello igitti,
Make sure that the official release firmware 1.0.1 is installed on your flipper zero and then you can download and manually copy the fixed fap file from here: [https://github.com/vladin79/unitemp-flipperzero/releases/download/1.6/unitemp.fap](url). I'm using it at the moment and it is working without problems.

**Comment by igitti** [comment]
Thanks vladin, I have already installed the official firmware 1.1.2. When I copy the fap file to apps/GPIO using qFlipper and try to start the app, the previous "Error: Outdated App" is shown again.
I seems that just copy does not install the app. On the flipper it is shown with a ? icon with the label "unitemp" just as the filename.
When I installed the broken version 1.5 using the browser, it was shown as "Temp sensors reader" with its correct icon (if I remember correctly). What am I doing wrong?

**Comment by vladin79** [comment]
Manually copying the fap file actually installs it. The ? icon and outdated error are due to an older version of the app.
I tried and copied the old version 1.5 to my flipper and I received the same outdated error. When I copy the file I fixed, it works normally.
Did you used the fixed file from the link I gave you above?

**Comment by igitti** [comment]
Your 1.6 latest fap file wotks, thanks for that!
My assumption about copying vs. installing was wrong. Obvisouly the the api versions must match for correct installation.
Hopefully your pull request will be merged soon.

**Comment by vladin79** [comment]
> Obvisouly the the api versions must match for correct installation.

That's correct. Apps are built for a specific API version, which is stored inside the fap. When the fap is loaded from the SD card, the required API version inside it is checked against the API version of the firmware. If the two versions don't match, an error is issued. This is explained in more details in the [official developer docs](https://developer.flipper.net/flipperzero/doxygen/apps_on_sd_card.html).
