### ISSUE TITLE
Preload Failed API version mismatch on latest firmware

### ISSUE THREAD

**Issue by koalazak** [quen0n/unitemp-flipperzero#6]
Hello,
Im getting the `Preload Failed API version mismatch` in the latest firmware. Is there something that I can do to fix it myself?

![version](https://user-images.githubusercontent.com/8185092/223708471-f1472fd1-46c7-4c1d-b9d9-00813e628451.png)

regards,

**Comment by koalazak** [comment]
fixed rebuilding it:

1) Download latest firmware and `git checkout <latest_tag>`
2) Put content of this repository in `./applications_user/unitemp` directory
3) run `./fbt fap_dist` on firmware directory
4) copy `./dist/xxx/apps/GPIO/unitemp.fap into flipper `SD card/apps/GPIO`

**Comment by quen0n** [comment]
Hello. I updated the version of the API of the application, now this problem should not occur
