### ISSUE TITLE
Discord link on readme is not working

### ISSUE THREAD

**Issue by koalazak** [quen0n/unitemp-flipperzero#7]
Hello,

the Discord link on readme is not working for users that are not already in the server. I thing you should put the server/invite link instead of the channel link.
<img width="663" alt="Screen Shot 2023-03-08 at 09 05 33" src="https://user-images.githubusercontent.com/8185092/223709052-c72ab46e-5f07-4697-b73a-113c3e2f130f.png">

thank you

**Comment by quen0n** [comment]
Hello. The link points to a thread on the official Flipper Zero discord server. Ok, I'll add an invitation link to the description.
